#!/usr/bin/sh

[ -f ~/.Xresources ] && xrdb -merge -I$HOME ~/.Xresources

# E.g. for Japanese input, export USE_SCIM=1 before this script.
# SCIM should be started automatically when logging in but if it isn't: scim -d
if [ "$USE_SCIM" = 1 ]
then
    export XMODIFIERS=@im=SCIM
    export GTK_IM_MODULE=scim
    export QT_IM_MODULE=scim
fi

# Enable X fonts.
export GDK_USE_XFT=1
export QT_XFT=1

# Qt5.7 no longer supports GTK styles so to get something reasonable (i.e. dark color scheme)
# one must use qt5ct to change the look of Qt5 applications.
export QT_QPA_PLATFORMTHEME=qt5ct

# Set default standby, suspend, off timeouts for DPMS. If using a television, DPMS is probably not supported but the signal is turned off so the TV power management may set standby.
xset dpms 900 0 0
# Disable screensaver.
xset s off

# Restore ALSA state (volumes etc.) if saved.
[ -f ~/.asound.state ] && /usr/bin/alsactl restore -f ~/.asound.state 2>/dev/null

# Link .cache under .tmpfs and .tmpfs itself somewhere under a tmpfs, for example $XDG_RUNTIME_DIR.
[ "$XDG_RUNTIME_DIR" ] && [ ! -e ~/.tmpfs ] && ln -s $XDG_RUNTIME_DIR ~/.tmpfs
mkdir -p $(readlink ~/.tmpfs) 2>/dev/null
mkdir -p $(readlink ~/.cache) 2>/dev/null
which mpv >/dev/null 2>&1 && [ -d ~/.cache ] && [ ! -e ~/.cache/mpvfifo ] && mkfifo ~/.cache/mpvfifo
# Persist sessions if directory exists.
[ -d ~/.sessions ] && [ ! -e ~/.cache/sessions ] && ln -sf ~/.sessions ~/.cache/sessions
# Persist pip cache if directory exists.
[ -d ~/.pip-cache ] && [ ! -e ~/.cache/pip ] && ln -sf ~/.pip-cache ~/.cache/pip

# This temporary directory is needed if using mhwaveedit.
which mhwaveedit >/dev/null 2>&1 && mkdir -p /tmp/mhwaveedit

# This application does absolutely nothing, it just waits to be killed, keeping X alive.
# It is as stable as it gets, even if the real session manager might be unstable.
# The code consists of a single pause() call.
lastone=$(ls /opt/programs/pause/pause 2>/dev/null)

# Need to set to XFCE so that log out etc. works correctly when using XFCE panel. Otherwise X-Generic would be more correct.
export XDG_CURRENT_DESKTOP="XFCE"

# To use this file as an Xsession file, create a link:
# ln -s ~/.xinitrc ~/.xsession && chmod +x ~/.xinitrc
if [ $(basename "$0") = ".xsession" ] || [ ! "$lastone" ]
then
    exec xfce4-session
else
    xfce4-session &
    exec $lastone
fi
