#!/bin/sh
# Use PlatformIO via a script.
# One may install PlatformIO locally and use this script from a
# directory in PATH, for example from /opt/bin.
# Everything then basically works as if pio was installed globally.
# As a bonus, there is a pip install shortcut for the script.

piopath=~/.local/bin/

if [ "$1" = "install" ]
then
    [ "$2" ] && piopath="$2"
    pip install --target="$piopath" -U platformio
    exit
fi

export PYTHONPATH="${PYTHONPATH}:$piopath"
env python $piopath/platformio "$@"
